### ISSUE TITLE
Microsoft account auth not working

### ISSUE THREAD

**Issue by ethanrock01** [urFate/Afk-Bot#2]
I have a second account I wanted to use for a bot here, which has already been migrated to Microsoft. The config is correct with my Microsoft email and password but no dice - always says incorrect username and password. I tried this by switching it to my Mojang account and it worked, but that's my main account. I migrated that account now (gonna have to do it eventually, anyways) to a different microsoft account but still, doesn't work. Any help here would be very much appreciated.

**Comment by urFate** [comment]
Fixed.
