### ISSUE TITLE
Bot incompatible with server mods

### ISSUE THREAD

**Issue by BLACKNAUTILOS** [urFate/Afk-Bot#33]
I tried to connect the bot on a vanilla mohist server and it worked but when I added the mods, it did not work

**Comment by urFate** [comment]
Working with the network stack in this project is entirely on the [Mineflayer](https://github.com/PrismarineJS/mineflayer) library. Accordingly, it is better to turn there for help.

**Comment by urFate** [comment]
I'm updated mineflayer module in last commit. It's probably fix problem.
