### ISSUE TITLE
Mojang Account Support Stopped

### ISSUE THREAD

**Issue by SqueakyParr0t** [urFate/Afk-Bot#39]
For some reason, minecraft mojang auth has been stopped, so I can't use this on my server without making myself not be able to play on the server. Is there a way to use microsoft account on a cracked server so that I don't have to use my own account?

**Comment by urFate** [comment]
Mojang accounts support stopped completely by Mojang. For offline servers you can enter bot username in `Username` field and keep `Password` and `Type` fields empty.

**Comment by SqueakyParr0t** [comment]
> 

Thanks your the best coder I've ever seen on Github 🥇 YOU DESERVE A FOLLOW
