### ISSUE TITLE
Leaving Type Field Blank Doesn't Work

### ISSUE THREAD

**Issue by SqueakyParr0t** [urFate/Afk-Bot#43]
I left the type field and password fields blank and typed the username in the username field. The bot won't join the server, even though it is cracked. Is there a way to fix this?

**Comment by urFate** [comment]
Can you provide bot logs?

**Comment by SqueakyParr0t** [comment]
I ran the code on replit. When I used version 1.19.3, this happened:
<img width="1159" alt="Screen Shot 2023-01-06 at 4 06 54 PM" src="https://user-images.githubusercontent.com/117523718/211100826-d547423f-f19b-41cb-81e4-374ccea8f30c.png">

When I replaced it with 1.19.2, the code just didn't run:
<img width="1169" alt="Screen Shot 2023-01-06 at 4 08 17 PM" src="https://user-images.githubusercontent.com/117523718/211100880-0eb3ff0b-5a34-4a83-8277-06310705a1ed.png">

**Comment by SqueakyParr0t** [comment]
the 1.19.2 finally ran but outputted:
<img width="1172" alt="Screen Shot 2023-01-06 at 4 26 00 PM" src="https://user-images.githubusercontent.com/117523718/211102882-5969f17d-7781-4573-8aba-cab917c156ec.png">

How do I fix this? The server was online, but the bot couldn't join.

**Comment by SqueakyParr0t** [comment]
Can you please also make a replit version on [replit.com](replit.com) so that I can just fork it and it will work?
Thanks!

**Comment by urFate** [comment]
Seems like Mineflayer supports only 1.19.2 at this moment. (Just need to wait update from developers)
What about your second picture it's strictly Replit moment. This is not a problem of our bot, but of the service itself.
I can assume that Replit it has some restrictions regarding Internet access for web applications. I have no ideas about that.

**Comment by SqueakyParr0t** [comment]
thanks
