### ISSUE TITLE
Stuck on server starting

### ISSUE THREAD

**Issue by G6F9** [urFate/Afk-Bot#44]
(https://user-images.githubusercontent.com/112145974/211137203-5405beba-53d4-48db-9a03-f71ca549ca46.png)

**Comment by G6F9** [comment]
![image](https://user-images.githubusercontent.com/112145974/211139137-fe70354e-1f62-4bef-9908-4fe6c0799948.png)
this too

**Comment by urFate** [comment]
[Mojang accounts service was stopped by minecraft developers.](https://github.com/urFate/Afk-Bot/issues/39)
Use microsoft account instead.
