### ISSUE TITLE
 unsupported protocol version: 1.19.3

### ISSUE THREAD

**Issue by darklord9201** [urFate/Afk-Bot#50]
**Not Working for 1.19.3**

**Screenshots**
![image](https://user-images.githubusercontent.com/6932017/212249767-4f9417e1-f995-4a1b-b5d7-d1b2b1eb6cb6.png)

**Comment by urFate** [comment]
Waiting for mineflayer update.

**Comment by urFate** [comment]
Fixed in [002c748](https://github.com/urFate/Afk-Bot/commit/002c748c1a9340b7ae9bf253af19449cca6e340d)
