### ISSUE TITLE
1.19.3 not working (for me atleast)

### ISSUE THREAD

**Issue by Minionguyjpro** [urFate/Afk-Bot#51]
I tried using this with a server that is 1.19.3, but it doesn't work.
I've tried:
Updating all NPM/Node modules.
Didn't help sadly...

**Comment by urFate** [comment]
It's minecraft-protocol issue. So just need to wait update from developers.

**Comment by Minionguyjpro** [comment]
> It's minecraft-protocol issue. So just need to wait update from developers.

Nevermind, I let it join using 1.19 and with ViaBackwards plugin. One more question, do you know how to fix reconnect issue? When it reconnects it does in a time that is shorter than 1 second. I have putted the value very high, but it didn't help.

**Comment by jingfengsama** [comment]
still not work at 1.19.3

**Comment by jingfengsama** [comment]
![image](https://user-images.githubusercontent.com/78785393/215307496-4149a23e-7a41-4019-b634-2477f3614988.png)
and for some reason i cant download 1.3.0 version.
![image](https://user-images.githubusercontent.com/78785393/215307529-e11dfe42-8e59-4e99-bac8-7e2416666e79.png)
when i clicked download

**Comment by urFate** [comment]
Fixed in [2cd58d1](https://github.com/urFate/Afk-Bot/commit/2cd58d1dd42eb44813b364a662f79a2c778c507d).
