### ISSUE TITLE
How to run this on cloud server

### ISSUE THREAD

**Issue by Banicodes** [urFate/Afk-Bot#53]
I want to run this with my pc shutdown? What should i do

**Comment by urFate** [comment]
You can rent VPS from any hosting, connect to it via SSH, install `screen` util and run bot in screen session to keep it running when you disconnected from your VPS.
[How to use screen in Linux](https://www.google.com/search?q=How+to+use+screen+in+linux)

**Comment by Banicodes** [comment]
I 

> You can rent VPS from any hosting, connect to it via SSH, install `screen` util and run bot in screen session to keep it running when you disconnected from your VPS. [How to use screen in Linux](https://www.google.com/search?q=How+to+use+screen+in+linux)

I tried using render and forking this project... I kept the command to npm install node
But it says Module Not found:"minecraft-data" error
