### ISSUE TITLE
need a feature that bot can kill monsters for akf farm

### ISSUE THREAD

**Issue by jingfengsama** [urFate/Afk-Bot#59]
**Is your feature request related to a problem? Please describe.**
I tried to AFK at monster farm while [anti-afk'].hit  true. 
However, the bot only swing arm but can't hit monsters so can't kill monsters.

**Describe the solution you'd like**
could the bot imitate the real hit?

**Describe alternatives you've considered**

**Additional context**

**Comment by urFate** [comment]
Why bot uses artificial hit? - Mineflayer library requires target, to make real hit. In very many cases we don't have targets to hit them. As alternative we just swinging hand instead of hitting. 

As solution we can add sub option to automatically detect nearby reachable targets and hit them.

**Comment by urFate** [comment]
New feature now is decribed in [our new wiki](https://urfate.gitbook.io/afk-bot/bot-configuration).
