### ISSUE TITLE
crashed after running a while 

### ISSUE THREAD

**Issue by jingfengsama** [urFate/Afk-Bot#62]
version:1.3.2
mc server version: 1.19.3

log:
![image](https://user-images.githubusercontent.com/78785393/216338543-ecd360a3-f3c8-4f4d-9ce4-18bbce3789b6.png)
crashed after running a while （at most 1 hour ）

settings:
{
  "bot-account": {
    "username": "silenpen_jf",
    "password": "",
    "type": "mojang"
  },

  "server": {
    "ip": "dx.coreages.com",
    "port": 25565,
    "version": "1.19.3"
  },

  "position": {
    "enabled": false,
    "x": 0,
    "y": 0,
    "z": 0
  },

  "utils": {
    "auto-auth": {
      "enabled": true,
      "password": "whitealbum2"
    },

    "anti-afk": {
      "enabled": true,
      "sneak": false,
      "jump": false,
      "rotate": false,

      "hit": {
        "enabled": true,
        "delay": 1000,
        "attack-mobs": true
      },

      "circle-walk": {
        "enabled": false,
        "radius": 2
      }
    },

    "chat-messages": {
      "enabled": false,
      "repeat": false,
      "repeat-delay": 60,

      "messages": [
        "I'm an afk bot",
        "My owner is jf",
        "I want be alone "
      ]
    },

    "chat-log": false,
    "auto-reconnect": true,
    "auto-reconnect-delay": 5000
  }
}

crashed on cloud server too. (The only difference is that "hit" is not enabled)

**Comment by jingfengsama** [comment]
1.2 version not crash

**Comment by urFate** [comment]
Did you use it on AFK farm or something else?

**Comment by jingfengsama** [comment]
one used but another just stay at home&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "George ***@***.***&gt;; 
发送时间: 2023年2月3日(星期五) 凌晨2:28
收件人: ***@***.***&gt;; 
抄送: "Azure ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [urFate/Afk-Bot] crashed after running a while  (Issue #62)





 
Did you use it on AFK farm or something else?

**Comment by jingfengsama** [comment]
> Did you use it on AFK farm or something else? It's very difficult to say what is the root of your problem. If it's applicable, you can just disable mob hit feature.
> 
> It would be great if you sent a list/screenshot of the nearest mobs to the bot within a radius of 6 blocks, but I don't think this is already possible.

one used on afk farm but another just stay at home

**Comment by jingfengsama** [comment]
i mean both of them crashed with the same crash log.

**Comment by jingfengsama** [comment]
{
  "bot-account": {
    "username": "jfmiao",
    "password": "",
    "type": "mojang"
  },

  "server": {
    "ip": "dx.coreages.com",
    "port": 25565,
    "version": "1.19.3"
  },

  "position": {
    "enabled": false,
    "x": 0,
    "y": 0,
    "z": 0
  },

  "utils": {
    "auto-auth": {
      "enabled": true,
      "password": "whitealbum2"
    },

    "anti-afk": {
      "enabled": false,
      "sneak": false,
      "jump": false,
      "rotate": false,

      "hit": {
        "enabled": false,
        "delay": 1000,
        "attack-mobs": false 
      },

      "circle-walk": {
        "enabled": false,
        "radius": 2
      }
    },

    "chat-messages": {
      "enabled": false,
      "repeat": false,
      "repeat-delay": 60,

      "messages": [
        "I'm a regular player ",
        "My owner is urFate_ ",
        "I want be alone ",
        "Visit my GitHub page! (urFate/Afk-Bot)"
      ]
    },

    "chat-log": false ,
    "auto-reconnect": true,
    "auto-reconnect-delay": 5000
  }
}

cloud server 's setting ,crashed too

**Comment by Minionguyjpro** [comment]
I think I got the same error, the bot was working first but since a few days it randomly leaves after like 8 hours.

**Comment by Minionguyjpro** [comment]
I think it is an issue with the Node.js modules, and not the repo itself. But I am not sure...

**Comment by urFate** [comment]
> I think it is an issue with the Node.js modules, and not the repo itself. But I am not sure...

Seems like it is. I'm really can't figure out what happened from this logs. E.g. somewhere in mineflayer, some entity is null, and blah, blah, blah... 

So i've recommend open issue in [mineflayer](https://github.com/PrismarineJS/mineflayer/issues) repo, idk...

**Comment by jingfengsama** [comment]
> > I think it is an issue with the Node.js modules, and not the repo itself. But I am not sure...
> 
> Seems like it is. I'm really can't figure out what happened from this logs. E.g. somewhere in mineflayer, some entity is null, and blah, blah, blah...
> 
> So i've recommend to create new issue in [mineflayer](https://github.com/PrismarineJS/mineflayer/issues) repo, idk...

some clues here:
crash periodically whether hit mobs is on nor off.

certainly not work while rebirth in the main town

I have not joined other servers to find if the afk bot runs well.

bot of 1.2 version do not crash while 1.3 crashes no matter what configuration.

**Comment by jingfengsama** [comment]
find that two bots crashed at the same time on different windows servers.
may related to the data transmission between certain mc server and users. 

you can check these by login this server(only need to regist).

**Comment by urFate** [comment]
> > > I think it is an issue with the Node.js modules, and not the repo itself. But I am not sure...
> > 
> > 
> > Seems like it is. I'm really can't figure out what happened from this logs. E.g. somewhere in mineflayer, some entity is null, and blah, blah, blah...
> > So i've recommend to create new issue in [mineflayer](https://github.com/PrismarineJS/mineflayer/issues) repo, idk...
> 
> some clues here: crash periodically whether hit mobs is on nor off.
> 
> certainly not work while rebirth in the main town
> 
> I have not joined other servers to find if the afk bot runs well.
> 
> bot of 1.2 version do not crash while 1.3 crashes no matter what configuration.

1.2 Version have outdated mineflayer, and outdated dependencies. So this bug could appear in latest releases of mineflayer. As temporary solution you can downgrade mineflayer in `package.json` to 4.1.0 which is used in 1.2 release. But you will lose 1.19.3 support.

**Comment by jingfengsama** [comment]
> > > > I think it is an issue with the Node.js modules, and not the repo itself. But I am not sure...
> > > 
> > > 
> > > Seems like it is. I'm really can't figure out what happened from this logs. E.g. somewhere in mineflayer, some entity is null, and blah, blah, blah...
> > > So i've recommend to create new issue in [mineflayer](https://github.com/PrismarineJS/mineflayer/issues) repo, idk...
> > 
> > 
> > some clues here: crash periodically whether hit mobs is on nor off.
> > certainly not work while rebirth in the main town
> > I have not joined other servers to find if the afk bot runs well.
> > bot of 1.2 version do not crash while 1.3 crashes no matter what configuration.
> 
> 1.2 Version have outdated mineflayer, and outdated dependencies. So this bug could appear in latest releases of mineflayer. As temporary solution you can downgrade mineflayer in `package.json` to 4.1.0 which is used in 1.2 release. But you will lose 1.19.3 support.

thx, that  do ues

**Comment by urFate** [comment]
Updated mineflayer to 4.8.1 which can fix this issue.
